### PR TITLE
add support for homogeneous transformation matrices

### PR DESCRIPTION
**Pull request by barcode**
also added some temp files to gitignore

### CODE REVIEW

**Comment by haudren** [comment]
Thanks for the submission! I'm not sure that we really need to extend the `.gitignore`, but it doesn't hurt.

My only problem is that you invert the rotation part of your homogeneous matrix when converting to PTransform. I understand that this is necessary to properly operate within `RBDyn`, but I am of the opinion that sva should remain "surprise-free", as I stated in #5  . I am still on the fence as to where/how this conversion is most appropriate and welcome discussion.

**Comment by barcode** [comment]
i extended gitignore to prevent me from accidentally pushing these files.  
i transpose the rotation since the "default" homogeneous transformation matrices need the rotation this way.
i think it would be more surprising if the rotations were not transposed.  
in fact i was confused for some time until i noticed that all rotations were the wrong way around (at least if you are used to work with homogeneous transformation matrices).  
also i did not need this conversion  to properly operate within `RBDyn` but to use it with a different framework.

**Comment by barcode** [comment]
will this be merged or what needs to be changed so it can be merged?  
i could change the ctor to a `fromHomogeneousTransform()` function (this is just as QString does its constructors).  
i can't really remove the transpose (then the result would not be a homogeneous transformation matrix).  
i just would like to know if this won't be merged (then i will add this fix to the framework calling this lib).

**Comment by haudren** [comment]
Sorry, I haven't had time to concert with @gergondet , but I definitely think that this should be merged. Maybe we should had a flag of sorts to allow for conversion without transposition? And should we put this in a separate header (maybe `conversions.hxx`)  ?

**Comment by gergondet** [comment]
The one thing that bothers me is that:

```cpp
auto pt1 = sva::PTransformd(hom);
auto p2 = sva::PTransformd(hom.rotation(), hom.vector());
/* Here pt1 != pt2 if hom.rotation() is not symmetric */
```

I think moving the function to a separate header/namespace (e.g `Conversions.h` and `sva::conversions`) makes more sense (with an optional parameter to specify whether the homogeneous matrix is provided with a different convention), as it expresses better that while working with SVA objects a single convention is adopted.

That could look like:

```cpp
auto pt = sva::conversions::fromHomogenousMatrix(m4, /*sva::conversions::RightHanded */);
```

**Comment by haudren** [comment]
Well the rotation matrix will only be symmetric if it is the identity so we can safely consider that `pt1 != pt2` in general. I feel that your solution is the most appropriate. @barcode : Do you have time to implement this? Else I will get to it during the week.

**Comment by barcode** [comment]
i have time to do this.  
just to make sure, are you using a left handed coordinate system or are you multiplying your vectors from the left side to your matrices while using a right handed coordinate system?  
i can't really tell from a rotation matrix alone, since in both cases this would be a transpose.

**Comment by haudren** [comment]
The rule for a `transform * vector` is:
```cpp
out.angular() = pt.rotation()*in.angular();
out.linear()  = pt.rotation()*in.linear() - pt.translation().cross(in.angular());
```
Which is, if I'm not mistaken a left-handed coordinate system. Similarly, you can play with `sva::RotX` and co. to check:
```
>>> sva.RotX(pi/4)
1 0 0
0 0.707107 0.707107
0 -0.707107 0.707107
```
Which is [left-handed](http://answers.unity3d.com/storage/temp/12048-lefthandedtorighthanded.pdf)

**Comment by haudren** [comment]
Note: I just implemented something on my own branch:
https://github.com/haudren/SpaceVecAlg/commit/feea12da1a2605cbaf8d4efc0989319d3275658f

Feel free to use it! It would be nice to also add a small test.

**Comment by barcode** [comment]
your version looks good.  
i fixed a few minor issues and added a test case.  
i would propose to merge that branch after my fixes are merged.

**Comment by haudren** [comment]
Closed by #15

**Pull request closed without merging**
